### ISSUE TITLE
Enabler: Add build process

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/launch-extension-eddl#2]
# Create a build process

In order to make sure we are deploying minified code and making things easier to develop, we need to introduce some sort of build process. 

MUST HAVES:
* minify our code
* output assets needed for [Reactor Packager](https://github.com/adobe/reactor-packager) to a `pre-package` folder that allows for reactor-packager to work

NICE TO HAVE:
* Test the code for things not available under supported Launch browsers
* Babel so we do not need to code like animals

> **ESTIMATE** NN

**Comment by arcepaul** [comment]
@bryanpizzillo 
Approach-wise, I am going to try starting with rollup js as the bundler to handle the minification and output to the pre-package folder and starting off with a basic babel/preset-env setup.  We'll see how far that gets me.

**Comment by bryanpizzillo** [comment]
It looks like Adobe will minify your code for you.  So we do not need Babel. 

Oh and we will still have to code like animals.
